import { createFileRoute } from "@tanstack/react-router";
import { Sparkles } from "lucide-react";
import { useState } from "react";

import { AiOutput } from "@/components/AiOutput";
import { AppShell } from "@/components/AppShell";
import { useAiTool } from "@/components/useAiTool";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

export const Route = createFileRoute("/planner")({
  head: () => ({
    meta: [
      { title: "AI Task Planner — AI_Workplace_productivity_Assistant" },
      {
        name: "description",
        content:
          "Turn goals and workloads into a prioritised, time-blocked plan with dependencies and milestones.",
      },
      { property: "og:title", content: "AI Task Planner — AI_Workplace_productivity_Assistant" },
      { property: "og:description", content: "Prioritised, time-blocked plans generated by AI." },
    ],
  }),
  component: PlannerPage,
});

const HORIZONS = ["Today", "This week", "Two weeks", "This month", "This quarter"];
const METHODS = ["Eisenhower matrix", "MoSCoW", "Time blocking", "Simple priority list"];

function PlannerPage() {
  const { output, setOutput, loading, error, generate } = useAiTool();
  const [goal, setGoal] = useState("");
  const [tasks, setTasks] = useState("");
  const [hours, setHours] = useState("6");
  const [horizon, setHorizon] = useState("This week");
  const [method, setMethod] = useState("Time blocking");

  const submit = () =>
    generate(
      "You are an executive productivity coach. Produce realistic, prioritised plans in markdown with a priority table, a day-by-day schedule, dependencies, and a 'risks & buffers' note. Keep workloads within the stated capacity.",
      [
        `Primary goal: ${goal}`,
        `Tasks and commitments:\n${tasks}`,
        `Planning horizon: ${horizon}`,
        `Available focus hours per day: ${hours}`,
        `Prioritisation method: ${method}`,
      ].join("\n"),
    );

  return (
    <AppShell
      title="AI Task Planner"
      description="Prioritise your workload and get a realistic, time-blocked plan."
    >
      <div className="grid gap-6 lg:grid-cols-2">
        <Card className="space-y-5 p-5" style={{ boxShadow: "var(--shadow-soft)" }}>
          <div className="space-y-2">
            <Label htmlFor="goal">Main goal</Label>
            <Input
              id="goal"
              value={goal}
              onChange={(e) => setGoal(e.target.value)}
              placeholder="Ship the client onboarding revamp"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="tasks">Tasks, deadlines and commitments</Label>
            <Textarea
              id="tasks"
              value={tasks}
              onChange={(e) => setTasks(e.target.value)}
              placeholder={"- Finalise onboarding copy (due Thu)\n- 3 client calls Tuesday\n- Review vendor contract"}
              className="min-h-40"
            />
          </div>
          <div className="grid gap-4 sm:grid-cols-3">
            <div className="space-y-2">
              <Label>Horizon</Label>
              <Select value={horizon} onValueChange={setHorizon}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {HORIZONS.map((h) => (
                    <SelectItem key={h} value={h}>
                      {h}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>Method</Label>
              <Select value={method} onValueChange={setMethod}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {METHODS.map((m) => (
                    <SelectItem key={m} value={m}>
                      {m}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="hours">Focus hrs/day</Label>
              <Input
                id="hours"
                type="number"
                min={1}
                max={12}
                value={hours}
                onChange={(e) => setHours(e.target.value)}
              />
            </div>
          </div>
          <Button onClick={submit} disabled={loading || tasks.trim().length < 5} className="w-full">
            <Sparkles className="size-4" />
            {loading ? "Planning…" : "Build my plan"}
          </Button>
        </Card>

        <AiOutput
          value={output}
          onChange={setOutput}
          loading={loading}
          error={error}
          placeholder="Your prioritised plan will appear here."
          filename="task-plan.md"
        />
      </div>
    </AppShell>
  );
}
